version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PROD_DATABASE_URL=${PROD_DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PROD_HOST=${REDIS_PROD_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PORT=${PORT}
      - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - 3001:3001
    command: ["./entrypoint.sh"]
    restart: unless-stopped


  redis:
    container_name: redis
    image: 'redislabs/rejson:2.0.0'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - 6381:6379
    volumes:
      - redis-data:/data
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:15.5-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
