version: '3.8'

services:
  redis:
    image: 'redislabs/rejson:2.0.0'
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  # postgres:
  #   image: "postgres:12.2"      
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres

volumes:
  redis-data:
