version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PROD_DATABASE_URL=${PROD_DATABASE_URL}
    ports:
      - 3001:3001
    command: ["./entrypoint.sh"]

  redis:
    image: 'redislabs/rejson:2.0.0'
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
