version: '3.8'

services:
  redis:
    image: 'redislabs/rejson:2.0.0'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      # - ./generate_config.sh:/usr/local/etc/redis/generate_config.sh
      # - ./redis.template.conf:/usr/local/etc/redis/redis.template.conf
      # - ./redis.template.conf:/redis.template.conf
    # entrypoint: ./generate_config.sh
    # command: ['./generate_config.sh']
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
