version: '3.8'

services:
  redis:
    image: 'redislabs/rejson:2.0.0'
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
