FROM alpine AS builder

# ARG REDIS_PASSWORD="${REDIS_PASSWORD}"
COPY .env .env
RUN export $(cat .env | xargs)
RUN echo "requirepass $REDIS_PASSWORD" > redis.conf


FROM redislabs/rejson:2.0.0

COPY --from=builder /redis.conf /usr/local/etc/redis/redis.conf

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]


# COPY redis.template.conf /usr/local/etc/redis/redis.template.conf
# COPY redis.template.conf /usr/local/bin/redis.template.conf
# COPY generate_redis.sh /usr/local/bin/
# RUN chmod +x /usr/local/bin/generate_redis.sh



# CMD ["generate_redis.sh"]
